name: Daily Limiteds Update

on:
  workflow_dispatch:      # manual trigger
  schedule:
    - cron: '0 6 * * *'   # daily at 6 AM UTC

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Fetch latest limiteds
        run: python fetch_limiteds.py

      - name: Commit new posts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add _posts
          git commit -m "chore: update limiteds $(date -u +'%Y-%m-%d')" || echo "No new posts"

      - name: Push changes using GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # rewrite origin to include the token
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/miqflur/miqflur.github.io.git
          git push origin main
