# .github/workflows/update.yml

name: Daily Limiteds Update

# Trigger manually or every day at 6 AM UTC
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

# Grant this workflow write access so it can push commits
permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Fetch latest limiteds
        run: python fetch_limiteds.py

      - name: Commit new posts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add _posts
          git commit -m "chore: update limiteds $(date -u +'%Y-%m-%d')" || echo "No new posts"

      - name: Push changes using PAT
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git
          git push
