name: Daily Limiteds Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install requests
        run: pip install requests

      - name: Fetch latest limiteds
        run: python fetch_limiteds.py

      - name: Commit new posts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add _posts
          git commit -m "chore: update limiteds $(date -u +'%Y-%m-%d')" || echo "No new posts"

      - name: Push changes
        run: git push origin main
